acme_task:
    resource: "@AcmeTaskBundle/Controller/"
    type:     annotation
    prefix:   /task

acme_store:
    resource: "@AcmeStoreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
